version: "3.8"
services:
  backend:
    build:
      context: ./server
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - appdata:/var/www/
    ports:
      - "5000:5000"
    environment:
      WOODCHUCK_SETTINGS: /app/server.cfg
    networks:
      - frontend
      - backend
    
  frontend:
    build:
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend

  
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  appdata:
    driver: local