// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9b5329839558a78550bf078c3e5f323c2f0f3b86/react-addons-linked-state-mixin/index.d.ts
declare module 'react-addons-linked-state-mixin' {
// Type definitions for React (react-addons-linked-state-mixin) 0.14
// Project: http://facebook.github.io/react/
// Definitions by: Asana <https://asana.com>, AssureSign <http://www.assuresign.com>, Microsoft <https://microsoft.com>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.1

import { Mixin } from 'react';

var LinkedStateMixin: LinkedStateMixin.LinkedStateMixin;
type LinkedStateMixin = LinkedStateMixin.LinkedStateMixin;
export = LinkedStateMixin;

namespace LinkedStateMixin {
	export interface ReactLink<T> {
	    value: T;
	    requestChange(newValue: T): void;
	}

	export interface LinkedStateMixin extends Mixin<any, any> {
	    linkState<T>(key: string): ReactLink<T>;
	}
}

module 'react' {
    interface HTMLAttributes<T> {
        checkedLink?: LinkedStateMixin.ReactLink<boolean>;
        valueLink?: LinkedStateMixin.ReactLink<boolean | string | number>;
    }
}
}
