// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9b5329839558a78550bf078c3e5f323c2f0f3b86/react-addons-create-fragment/index.d.ts
declare module 'react-addons-create-fragment' {
// Type definitions for React (react-addons-create-fragment) 0.14
// Project: http://facebook.github.io/react/
// Definitions by: Asana <https://asana.com>, AssureSign <http://www.assuresign.com>, Microsoft <https://microsoft.com>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.1

import * as React from 'react';

export = createFragment;

function createFragment(object: { [key: string]: React.ReactNode }): React.ReactFragment;
}
