// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9b5329839558a78550bf078c3e5f323c2f0f3b86/react-addons-pure-render-mixin/index.d.ts
declare module 'react-addons-pure-render-mixin' {
// Type definitions for React (react-addons-pure-render-mixin) 0.14
// Project: http://facebook.github.io/react/
// Definitions by: Asana <https://asana.com>, AssureSign <http://www.assuresign.com>, Microsoft <https://microsoft.com>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.1

import { Mixin } from 'react';

var PureRenderMixin: PureRenderMixin;
export = PureRenderMixin;

interface PureRenderMixin extends Mixin<any, any> { }
}
